name: Update Public Suffix List
on:
  schedule:
    - cron: '0 10 * * *'

env:
  LC_ALL: "en_US.UTF-8"

jobs:
  update-psl:
    if: github.repository == 'line/armeria'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup-jdk-19
        name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: |
          ./gradlew --no-daemon --stacktrace :core:publicSuffixes

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Push updated public suffix list
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '-S'
          commit_message: Update public suffix list
          file_pattern: core/src/main/resources/com/linecorp/armeria/public_suffixes.txt
          commit_user_name: Meri Kim
          commit_user_email: dl_armeria@linecorp.com
          commit_author: Meri Kim <dl_armeria@linecorp.com>
