name: Publish Armeria site

on:
  push:
    tags:
      - armeria-*

env:
  LC_ALL: 'en_US.UTF-8'

jobs:
  publish-site:
    if: github.repository == 'line/armeria'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install svgbob_cli
        run: |
          sudo apt-get -y install cargo && cargo install svgbob_cli
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - id: setup-jdk-19
        name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build the site
        run: |
          ./gradlew --no-daemon --stacktrace  --max-workers=2 --parallel -PgithubToken=${{ secrets.GITHUB_TOKEN }} site

      - name: Deploy the site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/public
